name: golangci-lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Check for unused Golang imports
        uses: Jerome1337/gomod-action@v1.0.0

      - name: Update git secret
        run: git config --global url."https://${{ secrets.GIT_USER_NAME }}:${{ secrets.GIT_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.41

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0
          args: -v

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
