name: ut

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  # This workflow contains a single job called "unit_test"
  unit_test:
    name: test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update git secret
        run: git config --global url."https://${{ secrets.GIT_USER_NAME }}:${{ secrets.GIT_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Test
        run: go test -v -count 1 ./...
